#!/usr/bin/env python3
"""Compile files into the daemon as resources (daemon/webapp.h).

    embed_res.py OUT.c NAME=PATH [NAME=PATH ...]

Writes a C file defining, for each NAME, `const unsigned char NAME[]` holding
the file's bytes and `const size_t NAME_len`. The build runs it for the web
client's page and loader, which the daemon serves from inside its own binary
(docs/WEB.md); only the .wasm travels beside it.
"""
import sys

def main(argv):
    if len(argv) < 3:
        sys.stderr.write("usage: embed_res.py OUT.c NAME=PATH ...\n")
        return 2
    out = argv[1]
    parts = ["/* Generated by scripts/embed_res.py -- do not edit. */\n#include <stddef.h>\n"]
    for spec in argv[2:]:
        name, path = spec.split("=", 1)
        with open(path, "rb") as f:
            data = f.read()
        parts.append(f"const unsigned char {name}[] = {{\n")
        for i in range(0, len(data), 24):
            parts.append("    " + ",".join(str(b) for b in data[i:i + 24]) + ",\n")
        parts.append(f"    0 }};\nconst size_t {name}_len = {len(data)};\n")
    with open(out, "w") as f:
        f.write("".join(parts))
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
