#!/usr/bin/env python3
# Dev-time icon baker: flatten the vendored Lucide SVGs (third_party/lucide/icons)
# into platform-agnostic cubic-bezier path data in client/shared/icons.{h,c}.
#
# Lucide icons are ISC-licensed line icons on a 24x24 viewBox, stroked (width 2,
# round caps/joins). We flatten every element (path/circle/rect/line/polyline) to
# Move/Line/Cubic/Close verbs in that 24x24 space; each client strokes them with
# its native vector API. Not shipped at runtime — only the generated icons.c is.
#
#   pip install --break-system-packages svgelements
#   python3 scripts/gen_icons.py
import os
from svgelements import SVG, Path, Move, Line, Close, CubicBezier, QuadraticBezier, Arc, Shape

# (enum suffix, lucide file) in enum order.
ICONS = [
    ("HOME",     "house"),
    ("DMS",      "message-square"),
    ("ACTIVITY", "activity"),
    ("FILE",     "file"),
    ("BOOKMARK", "bookmark"),
    ("ELLIPSIS", "ellipsis"),
    ("SETTINGS", "settings"),
    ("PLUS",     "plus"),
    ("BELL",     "bell"),
    ("USER",     "circle-user"),
    ("SQUARE_PEN","square-pen"),
    ("SEARCH",   "search"),
    ("SEND",     "send"),
    ("SMILE",    "smile"),
    ("AT",       "at-sign"),
    ("DOWNLOAD", "download"),
]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SVGDIR = os.path.join(ROOT, "third_party", "lucide", "icons")
# Icons we drew ourselves, in Lucide's conventions but not Lucide's work, so
# they live outside third_party and the ISC attribution there stays accurate.
LOCALDIR = os.path.join(ROOT, "client", "shared", "icons_src")

def svg_for(name):
    a = os.path.join(SVGDIR, name + ".svg")
    return a if os.path.exists(a) else os.path.join(LOCALDIR, name + ".svg")

def flatten(svgpath):
    """Return a list of verb tuples in 24x24 space."""
    out = []
    svg = SVG.parse(svgpath)
    for el in svg.elements():
        if not isinstance(el, Shape):
            continue
        p = Path(el)
        for seg in p:
            if isinstance(seg, Move):
                out.append(("M", seg.end.x, seg.end.y))
            elif isinstance(seg, Line):
                out.append(("L", seg.end.x, seg.end.y))
            elif isinstance(seg, Close):
                out.append(("Z",))
            elif isinstance(seg, CubicBezier):
                out.append(("C", seg.control1.x, seg.control1.y,
                                 seg.control2.x, seg.control2.y, seg.end.x, seg.end.y))
            elif isinstance(seg, QuadraticBezier):
                s, c, e = seg.start, seg.control, seg.end
                out.append(("C", s.x + 2/3*(c.x - s.x), s.y + 2/3*(c.y - s.y),
                                 e.x + 2/3*(c.x - e.x), e.y + 2/3*(c.y - e.y), e.x, e.y))
            elif isinstance(seg, Arc):
                for cub in seg.as_cubic_curves():
                    out.append(("C", cub.control1.x, cub.control1.y,
                                     cub.control2.x, cub.control2.y, cub.end.x, cub.end.y))
    return out

def fmt(v): return "%.3ff" % v

def emit_seg(t):
    op = ord(t[0])
    a = list(t[1:]) + [0.0] * (6 - (len(t) - 1))
    return "{ %d, %s }" % (op, ", ".join(fmt(x) for x in a))

def main():
    per = [(name, flatten(svg_for(f))) for name, f in ICONS]

    h = ['/* Auto-generated by scripts/gen_icons.py from Lucide (ISC). Do not edit. */',
         '#ifndef OC_ICONS_H', '#define OC_ICONS_H', '#include <stdint.h>', '',
         '/* One stroked path verb in the 24x24 Lucide viewBox. op is an ASCII code:',
         ' * M=move L=line C=cubic(x0,y0,x1,y1,x2,y2) Z=close. */',
         'typedef struct { uint8_t op; float x0, y0, x1, y1, x2, y2; } oc_icon_seg;',
         'typedef struct { const oc_icon_seg *segs; int n; } oc_icon;',
         '#define OC_ICON_VIEWBOX 24.0f', '', 'enum {']
    for name, _ in ICONS:
        h.append('    OC_ICON_%s,' % name)
    h += ['    OC_ICON_COUNT', '};', '',
          'extern const oc_icon OC_ICONS[OC_ICON_COUNT];', '', '#endif /* OC_ICONS_H */', '']

    c = ['/* Auto-generated by scripts/gen_icons.py from Lucide (ISC). Do not edit.',
         ' * Lucide Icons and Contributors, ISC License; see third_party/lucide/LICENSE. */',
         '#include "icons.h"', '']
    for name, segs in per:
        c.append('static const oc_icon_seg SEG_%s[] = {' % name)
        for s in segs:
            c.append('    ' + emit_seg(s) + ',')
        c.append('};')
    c.append('')
    c.append('const oc_icon OC_ICONS[OC_ICON_COUNT] = {')
    for name, segs in per:
        c.append('    [OC_ICON_%s] = { SEG_%s, %d },' % (name, name, len(segs)))
    c += ['};', '']

    os.makedirs(os.path.join(ROOT, "client", "shared"), exist_ok=True)
    open(os.path.join(ROOT, "client", "shared", "icons.h"), "w").write("\n".join(h))
    open(os.path.join(ROOT, "client", "shared", "icons.c"), "w").write("\n".join(c))
    print("wrote client/shared/icons.{h,c}:", ", ".join("%s=%d" % (n, len(s)) for n, s in per))

if __name__ == "__main__":
    main()
