#!/usr/bin/env bash
# Regenerate third_party/ca-roots/ca_roots.c, the root certificates every
# outbound HTTPS client verifies against (ARCH-10).
#
# The roots are Mozilla's: the set Firefox trusts for websites, as curl
# extracts it from NSS's certdata.txt and publishes by date. They are compiled
# into the binaries rather than read from the host, so what the daemon and the
# clients trust is a build fact -- the same on every distribution, in a
# container with no ca-certificates package, and on Windows, which has no
# bundle on disk at all.
#
# The output is committed. The build reads it and never fetches anything; this
# script runs only when the roots are refreshed, which is part of cutting a
# release (docs/RELEASING.md). To refresh: take the newest dated extract and its
# published sum from https://curl.se/docs/caextract.html, set both below, run
# this, and commit the regenerated file -- its diff is the list of roots added
# and removed, one comment per root.
set -euo pipefail

CA_ROOTS_DATE="2026-09-25"
CA_ROOTS_SHA256="a41b5d356aea97a529fe27e0f7316d2f9d946d75927476cf9cf1b90637d00505"

cd "$(dirname "$0")/.."
PEM="$(mktemp)"
trap 'rm -f "$PEM"' EXIT
URL="https://curl.se/ca/cacert-${CA_ROOTS_DATE}.pem"

echo "update_ca_roots: downloading ${URL}"
curl -fsSL -o "$PEM" "$URL"
got="$(sha256sum "$PEM" | cut -d" " -f1)"
if [ "$got" != "$CA_ROOTS_SHA256" ]; then
  echo "update_ca_roots: SHA-256 MISMATCH for ${URL}" >&2
  echo "  expected ${CA_ROOTS_SHA256}" >&2
  echo "  got      ${got}" >&2
  exit 1
fi
echo "update_ca_roots: sha256 ok (${got})"

OUT="third_party/ca-roots/ca_roots.c"
mkdir -p "$(dirname "$OUT")"
{
  cat <<EOF
/*
 * Mozilla's trusted root certificates for TLS server authentication, as curl
 * extracts them: https://curl.se/ca/cacert-${CA_ROOTS_DATE}.pem
 * (SHA-256 ${CA_ROOTS_SHA256}).
 *
 * GENERATED by scripts/update_ca_roots.sh -- do not edit; rerun the script.
 * The certificate data is Mozilla's, under the Mozilla Public License 2.0.
 */

#include <stddef.h>

extern const char oc_ca_roots_pem[];
extern const size_t oc_ca_roots_pem_size;

/* Every root, PEM, one after another. mbedtls_x509_crt_parse takes the whole
 * buffer, terminating NUL included. */
const char oc_ca_roots_pem[] =
EOF
  # A name line is the one above its row of '='; each PEM line becomes a string
  # literal. A name is only ever a comment, so the two characters that could end
  # one are defused.
  awk '
    /^=+$/ { name = prev; gsub(/\*\//, "* /", name); printf "\n/* %s */\n", name; inpem = 0 }
    /^-----BEGIN CERTIFICATE-----$/ { inpem = 1 }
    inpem { printf "\"%s\\n\"\n", $0 }
    /^-----END CERTIFICATE-----$/ { inpem = 0 }
    { prev = $0 }
  ' "$PEM"
  cat <<EOF
;

const size_t oc_ca_roots_pem_size = sizeof oc_ca_roots_pem;
EOF
} > "$OUT"

n="$(grep -c 'BEGIN CERTIFICATE' "$OUT")"
echo "update_ca_roots: wrote ${OUT} (${n} roots, Mozilla as of ${CA_ROOTS_DATE})"
