/* Auto-generated by scripts/gen_icons.py from Lucide (ISC). Do not edit. */
#ifndef OC_ICONS_H
#define OC_ICONS_H
#include <stdint.h>

/* One stroked path verb in the 24x24 Lucide viewBox. op is an ASCII code:
 * M=move L=line C=cubic(x0,y0,x1,y1,x2,y2) Z=close. */
typedef struct { uint8_t op; float x0, y0, x1, y1, x2, y2; } oc_icon_seg;
typedef struct { const oc_icon_seg *segs; int n; } oc_icon;
#define OC_ICON_VIEWBOX 24.0f

enum {
    OC_ICON_HOME,
    OC_ICON_DMS,
    OC_ICON_ACTIVITY,
    OC_ICON_FILE,
    OC_ICON_BOOKMARK,
    OC_ICON_ELLIPSIS,
    OC_ICON_SETTINGS,
    OC_ICON_PLUS,
    OC_ICON_BELL,
    OC_ICON_USER,
    OC_ICON_SQUARE_PEN,
    OC_ICON_SEARCH,
    OC_ICON_SEND,
    OC_ICON_SMILE,
    OC_ICON_AT,
    OC_ICON_DOWNLOAD,
    OC_ICON_PIN,
    OC_ICON_COUNT
};

extern const oc_icon OC_ICONS[OC_ICON_COUNT];

#endif /* OC_ICONS_H */
